
import CMSnavbar from "../components/Cmsnavbar"
import Provider from "../utils/Provider"
import "./globals.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
        <CMSnavbar/>
        {children}
        </Provider>
        </body>
    </html>
  )
}
